create table if not exists public.daily_attendance (
  id bigint generated by default as identity primary key,
  participant_id bigint not null references public.participants(id) on delete cascade,
  date date not null,
  status text not null default 'unklar'
    check (status in ('anwesend', 'abgesagt', 'krank', 'sonstiger_ausfall', 'verspaetet', 'halbtags', 'unklar')),
  note text,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint daily_attendance_participant_date_unique unique (participant_id, date)
);

drop trigger if exists touch_daily_attendance_updated_at on public.daily_attendance;
create trigger touch_daily_attendance_updated_at
before update on public.daily_attendance
for each row execute function public.touch_updated_at();

alter table public.daily_attendance enable row level security;

drop policy if exists daily_attendance_select_active on public.daily_attendance;
create policy daily_attendance_select_active
on public.daily_attendance
for select
using (public.current_user_is_active());

drop policy if exists daily_attendance_insert_leadership on public.daily_attendance;
create policy daily_attendance_insert_leadership
on public.daily_attendance
for insert
with check (
  public.current_user_is_active()
  and public.current_user_role() in ('admin', 'technical_lead', 'assistant')
);

drop policy if exists daily_attendance_update_leadership on public.daily_attendance;
create policy daily_attendance_update_leadership
on public.daily_attendance
for update
using (
  public.current_user_is_active()
  and public.current_user_role() in ('admin', 'technical_lead', 'assistant')
)
with check (
  public.current_user_is_active()
  and public.current_user_role() in ('admin', 'technical_lead', 'assistant')
);

drop policy if exists daily_attendance_delete_admin_tech on public.daily_attendance;
create policy daily_attendance_delete_admin_tech
on public.daily_attendance
for delete
using (
  public.current_user_is_active()
  and public.current_user_role() in ('admin', 'technical_lead')
);

grant select, insert, update, delete on public.daily_attendance to authenticated;
grant usage, select on all sequences in schema public to authenticated;
