-- Finanzmodul: Ausgabenplanung, Buchhaltung und Belegablage
-- Additiv ausfuehren nach supabase/schema.sql.

create table if not exists public.procurement_plans (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null
    check (category in ('lebensmittel','haushalt','sprit','werkzeug','buero_doku','ausflug','sonstiges')),
  quantity numeric(10,2),
  unit text,
  needed_by date,
  priority text not null default 'mittel'
    check (priority in ('hoch','mittel','niedrig')),
  status text not null default 'bedarf'
    check (status in ('bedarf','zu_pruefen','freigegeben','zu_kaufen','gekauft','gestrichen')),
  estimated_amount numeric(12,2),
  responsible_role text,
  note text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  procurement_plan_id bigint references public.procurement_plans(id) on delete set null,
  expense_date date not null default current_date,
  title text not null,
  category text not null
    check (category in ('lebensmittel','haushalt','sprit','werkzeug','buero_doku','ausflug','sonstiges')),
  amount numeric(12,2) not null check (amount >= 0),
  currency text not null default 'EUR',
  paid_by_participant_id bigint references public.participants(id) on delete set null,
  paid_by_name text,
  payment_method text,
  receipt_file_path text,
  receipt_status text not null default 'fehlt'
    check (receipt_status in ('fehlt','vorhanden','pruefen')),
  accounting_status text not null default 'offen'
    check (accounting_status in ('offen','vollstaendig','zu_pruefen','eingereicht','verbucht')),
  description text,
  internal_note text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists procurement_plans_status_idx on public.procurement_plans(status);
create index if not exists procurement_plans_needed_by_idx on public.procurement_plans(needed_by);
create index if not exists expenses_expense_date_idx on public.expenses(expense_date);
create index if not exists expenses_category_idx on public.expenses(category);
create index if not exists expenses_accounting_status_idx on public.expenses(accounting_status);

drop trigger if exists touch_procurement_plans_updated_at on public.procurement_plans;
create trigger touch_procurement_plans_updated_at
before update on public.procurement_plans
for each row execute function public.touch_updated_at();

drop trigger if exists touch_expenses_updated_at on public.expenses;
create trigger touch_expenses_updated_at
before update on public.expenses
for each row execute function public.touch_updated_at();

alter table public.procurement_plans enable row level security;
alter table public.expenses enable row level security;

drop policy if exists "procurement_plans_select_manager" on public.procurement_plans;
create policy "procurement_plans_select_manager"
on public.procurement_plans for select
to authenticated
using (public.current_user_can_manage());

drop policy if exists "procurement_plans_insert_manager" on public.procurement_plans;
create policy "procurement_plans_insert_manager"
on public.procurement_plans for insert
to authenticated
with check (public.current_user_can_manage());

drop policy if exists "procurement_plans_update_manager" on public.procurement_plans;
create policy "procurement_plans_update_manager"
on public.procurement_plans for update
to authenticated
using (public.current_user_can_manage())
with check (public.current_user_can_manage());

drop policy if exists "expenses_select_manager" on public.expenses;
create policy "expenses_select_manager"
on public.expenses for select
to authenticated
using (public.current_user_can_manage());

drop policy if exists "expenses_insert_manager" on public.expenses;
create policy "expenses_insert_manager"
on public.expenses for insert
to authenticated
with check (public.current_user_can_manage());

drop policy if exists "expenses_update_manager" on public.expenses;
create policy "expenses_update_manager"
on public.expenses for update
to authenticated
using (public.current_user_can_manage())
with check (public.current_user_can_manage());

grant select, insert, update on public.procurement_plans to authenticated;
grant select, insert, update on public.expenses to authenticated;
grant usage, select on all sequences in schema public to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'expense-receipts',
  'expense-receipts',
  false,
  10485760,
  array['image/jpeg','image/png','image/webp','application/pdf']
)
on conflict (id) do update
set public = false,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "expense_receipts_select_manager" on storage.objects;
create policy "expense_receipts_select_manager"
on storage.objects for select
to authenticated
using (bucket_id = 'expense-receipts' and public.current_user_can_manage());

drop policy if exists "expense_receipts_insert_manager" on storage.objects;
create policy "expense_receipts_insert_manager"
on storage.objects for insert
to authenticated
with check (bucket_id = 'expense-receipts' and public.current_user_can_manage());

drop policy if exists "expense_receipts_update_manager" on storage.objects;
create policy "expense_receipts_update_manager"
on storage.objects for update
to authenticated
using (bucket_id = 'expense-receipts' and public.current_user_can_manage())
with check (bucket_id = 'expense-receipts' and public.current_user_can_manage());

drop policy if exists "expense_receipts_delete_manager" on storage.objects;
create policy "expense_receipts_delete_manager"
on storage.objects for delete
to authenticated
using (bucket_id = 'expense-receipts' and public.current_user_can_manage());
