-- Ideenlabor: Querverbindungen zwischen Mindmap-Knoten
-- Additive Erweiterung: keine bestehenden Tabellen, Spalten oder Policies werden geloescht.

create table if not exists public.idea_lab_links (
  id bigint generated by default as identity primary key,
  source_item_id bigint not null references public.idea_lab_items(id) on delete cascade,
  target_item_id bigint not null references public.idea_lab_items(id) on delete cascade,
  label text,
  delta1 jsonb,
  delta2 jsonb,
  created_by uuid default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint idea_lab_links_no_self_link check (source_item_id <> target_item_id)
);

create index if not exists idea_lab_links_source_idx on public.idea_lab_links(source_item_id);
create index if not exists idea_lab_links_target_idx on public.idea_lab_links(target_item_id);

alter table public.idea_lab_links enable row level security;

drop policy if exists "idea_lab_links_select_members" on public.idea_lab_links;
create policy "idea_lab_links_select_members"
  on public.idea_lab_links
  for select
  to authenticated
  using (public.current_user_is_idea_lab_member());

drop policy if exists "idea_lab_links_insert_members" on public.idea_lab_links;
create policy "idea_lab_links_insert_members"
  on public.idea_lab_links
  for insert
  to authenticated
  with check (public.current_user_is_idea_lab_member());

drop policy if exists "idea_lab_links_update_members" on public.idea_lab_links;
create policy "idea_lab_links_update_members"
  on public.idea_lab_links
  for update
  to authenticated
  using (public.current_user_is_idea_lab_member())
  with check (public.current_user_is_idea_lab_member());

drop policy if exists "idea_lab_links_delete_members" on public.idea_lab_links;
create policy "idea_lab_links_delete_members"
  on public.idea_lab_links
  for delete
  to authenticated
  using (public.current_user_is_idea_lab_member());

create or replace function public.touch_idea_lab_links_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_idea_lab_links_updated_at on public.idea_lab_links;
create trigger trg_idea_lab_links_updated_at
  before update on public.idea_lab_links
  for each row execute function public.touch_idea_lab_links_updated_at();

grant select, insert, update, delete on public.idea_lab_links to authenticated;
grant usage, select on sequence public.idea_lab_links_id_seq to authenticated;
