-- Ideenlabor fuer Andreas Zauner und Niklas Mahler
-- Additive Erweiterung: keine bestehenden Tabellen, Spalten oder Policies werden geloescht.

create table if not exists public.idea_lab_items (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  area text not null default 'general'
    check (area in ('website','personal','field','map','weather','finance','logistics','general')),
  item_type text not null default 'idea'
    check (item_type in ('idea','todo','decision','note')),
  status text not null default 'idea'
    check (status in ('idea','review','important','later','done','archived')),
  priority text not null default 'medium'
    check (priority in ('high','medium','low')),
  parent_id bigint references public.idea_lab_items(id) on delete set null,
  sort_order integer,
  x integer,
  y integer,
  created_by uuid default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idea_lab_items_parent_idx on public.idea_lab_items(parent_id);
create index if not exists idea_lab_items_area_status_idx on public.idea_lab_items(area, status);
create index if not exists idea_lab_items_updated_at_idx on public.idea_lab_items(updated_at desc);

alter table public.idea_lab_items
  alter column created_by set default auth.uid();

alter table public.idea_lab_items enable row level security;

create or replace function public.current_user_is_idea_lab_member()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select lower(coalesce(p.email, '')) in ('andreas-zauner@gmx.de', 'mahler1994niklas@web.de')
  from public.profiles p
  where p.id = auth.uid()
$$;

drop policy if exists "idea_lab_select_members" on public.idea_lab_items;
create policy "idea_lab_select_members"
  on public.idea_lab_items
  for select
  to authenticated
  using (public.current_user_is_idea_lab_member());

drop policy if exists "idea_lab_insert_members" on public.idea_lab_items;
create policy "idea_lab_insert_members"
  on public.idea_lab_items
  for insert
  to authenticated
  with check (public.current_user_is_idea_lab_member());

drop policy if exists "idea_lab_update_members" on public.idea_lab_items;
create policy "idea_lab_update_members"
  on public.idea_lab_items
  for update
  to authenticated
  using (public.current_user_is_idea_lab_member())
  with check (public.current_user_is_idea_lab_member());

drop policy if exists "idea_lab_delete_members" on public.idea_lab_items;
create policy "idea_lab_delete_members"
  on public.idea_lab_items
  for delete
  to authenticated
  using (public.current_user_is_idea_lab_member());

create or replace function public.touch_idea_lab_items_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_idea_lab_items_updated_at on public.idea_lab_items;
create trigger trg_idea_lab_items_updated_at
  before update on public.idea_lab_items
  for each row execute function public.touch_idea_lab_items_updated_at();

grant select, insert, update, delete on public.idea_lab_items to authenticated;
grant usage, select on sequence public.idea_lab_items_id_seq to authenticated;
