-- Kartenmodul fuer Lehrgrabung Kerpen-Manheim 2026
-- Nach supabase/schema.sql ausfuehren. Ergaenzt Layer, GeoJSON-Features und RLS.

create table if not exists public.map_layers (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  description text,
  color text not null default '#2d7dd2',
  symbol text,
  is_visible boolean not null default true,
  is_public boolean not null default true,
  sort_order integer not null default 100,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint map_layers_name_unique unique (name),
  constraint map_layers_color_check check (color ~ '^#[0-9A-Fa-f]{6}$')
);

create table if not exists public.map_features (
  id bigint generated by default as identity primary key,
  primary_layer_id bigint not null references public.map_layers(id) on delete restrict,
  title text not null,
  description text,
  geometry jsonb not null,
  geometry_type text not null check (geometry_type in ('Point','LineString','Polygon','MultiPoint','MultiLineString','MultiPolygon')),
  category text,
  status text not null default 'geplant' check (status in ('geplant','aktiv','prüfen','erledigt','archiv')),
  priority text not null default 'mittel' check (priority in ('hoch','mittel','niedrig')),
  responsible_role text,
  linked_task_id bigint references public.tasks(id) on delete set null,
  linked_participant_id bigint references public.participants(id) on delete set null,
  label text,
  properties jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint map_features_geometry_geojson_check check (geometry ? 'type' and geometry ? 'coordinates')
);

create table if not exists public.map_feature_layers (
  feature_id bigint not null references public.map_features(id) on delete cascade,
  layer_id bigint not null references public.map_layers(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (feature_id, layer_id)
);

drop trigger if exists touch_map_layers_updated_at on public.map_layers;
create trigger touch_map_layers_updated_at before update on public.map_layers for each row execute function public.touch_updated_at();
drop trigger if exists touch_map_features_updated_at on public.map_features;
create trigger touch_map_features_updated_at before update on public.map_features for each row execute function public.touch_updated_at();

alter table public.map_layers enable row level security;
alter table public.map_features enable row level security;
alter table public.map_feature_layers enable row level security;

drop policy if exists "map_layers_select_active" on public.map_layers;
create policy "map_layers_select_active" on public.map_layers for select to authenticated using (public.current_user_is_active() and (is_public or public.current_user_can_manage()));
drop policy if exists "map_layers_insert_admin" on public.map_layers;
create policy "map_layers_insert_admin" on public.map_layers for insert to authenticated with check (public.current_user_role() = 'admin');
drop policy if exists "map_layers_update_admin" on public.map_layers;
create policy "map_layers_update_admin" on public.map_layers for update to authenticated using (public.current_user_role() = 'admin') with check (public.current_user_role() = 'admin');
drop policy if exists "map_layers_delete_admin" on public.map_layers;
create policy "map_layers_delete_admin" on public.map_layers for delete to authenticated using (public.current_user_role() = 'admin');

drop policy if exists "map_features_select_active" on public.map_features;
create policy "map_features_select_active" on public.map_features for select to authenticated using (public.current_user_is_active() and exists (select 1 from public.map_layers layer where layer.id = map_features.primary_layer_id and (layer.is_public or public.current_user_can_manage())));
drop policy if exists "map_features_insert_editor" on public.map_features;
create policy "map_features_insert_editor" on public.map_features for insert to authenticated with check (public.current_user_role() in ('admin','technical_lead','assistant'));
drop policy if exists "map_features_update_editor" on public.map_features;
create policy "map_features_update_editor" on public.map_features for update to authenticated using (public.current_user_role() in ('admin','technical_lead','assistant')) with check (public.current_user_role() in ('admin','technical_lead','assistant'));
drop policy if exists "map_features_delete_manager" on public.map_features;
create policy "map_features_delete_manager" on public.map_features for delete to authenticated using (public.current_user_role() in ('admin','technical_lead'));

drop policy if exists "map_feature_layers_select_active" on public.map_feature_layers;
create policy "map_feature_layers_select_active" on public.map_feature_layers for select to authenticated using (public.current_user_is_active());
drop policy if exists "map_feature_layers_insert_editor" on public.map_feature_layers;
create policy "map_feature_layers_insert_editor" on public.map_feature_layers for insert to authenticated with check (public.current_user_role() in ('admin','technical_lead','assistant'));
drop policy if exists "map_feature_layers_delete_manager" on public.map_feature_layers;
create policy "map_feature_layers_delete_manager" on public.map_feature_layers for delete to authenticated using (public.current_user_role() in ('admin','technical_lead'));

grant select, insert, update, delete on public.map_layers to authenticated;
grant select, insert, update, delete on public.map_features to authenticated;
grant select, insert, delete on public.map_feature_layers to authenticated;
grant usage, select on all sequences in schema public to authenticated;
