-- Material- und Beschaffungsmodul. Additiv nach supabase/schema.sql ausfuehren.

create table if not exists public.material_items (
  id bigint generated by default as identity primary key,
  title text not null,
  procurement_source text not null check (procurement_source in ('lmu','lvr','privat')),
  category text not null check (category in ('dokumentation','fundverwaltung','feinwerkzeug','grobwerkzeug','wasser','it_foto','psa_erste_hilfe','infrastruktur','transport_lagerung','verbrauch','sonstiges')),
  target_quantity numeric(10,2),
  current_quantity numeric(10,2),
  unit text,
  status text not null default 'offen' check (status in ('offen','angefragt','zugesagt','beschafft','teilweise','fehlt','entfaellt')),
  priority text not null default 'mittel' check (priority in ('hoch','mittel','niedrig')),
  needed_by date,
  storage_location text,
  responsible_role text,
  note text,
  source_note text,
  archived_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists material_items_source_idx on public.material_items(procurement_source);
create index if not exists material_items_category_idx on public.material_items(category);
create index if not exists material_items_status_idx on public.material_items(status);
create index if not exists material_items_archived_idx on public.material_items(archived_at);

drop trigger if exists touch_material_items_updated_at on public.material_items;
create trigger touch_material_items_updated_at before update on public.material_items for each row execute function public.touch_updated_at();

alter table public.material_items enable row level security;

drop policy if exists "material_items_select_active" on public.material_items;
create policy "material_items_select_active" on public.material_items for select to authenticated using (public.current_user_is_active());

drop policy if exists "material_items_insert_manager" on public.material_items;
create policy "material_items_insert_manager" on public.material_items for insert to authenticated with check (public.current_user_can_manage());

drop policy if exists "material_items_update_manager" on public.material_items;
create policy "material_items_update_manager" on public.material_items for update to authenticated using (public.current_user_can_manage()) with check (public.current_user_can_manage());

grant select, insert, update on public.material_items to authenticated;
grant usage, select on all sequences in schema public to authenticated;

insert into public.material_items (title, procurement_source, category, target_quantity, unit, status, priority, storage_location, responsible_role, note, source_note)
values
('Befundblaetter, Zeichenblaetter, Probenblaetter, Fundzettel, Tagebuchvorlagen','lmu','dokumentation',null,null,'offen','hoch','Dokumentationskiste','Technische Grabungsleitung / Assistenz','Grosser Vorrat; vor Beginn drucken, nummerieren oder digital vorbereiten.','Materialplanung_Aufteilung_Uni_LVR.docx'),
('Klemmbretter','lmu','dokumentation',12,'Stk.','offen','mittel','Teamkisten / Dokumentationskiste','Assistenz','8-12 Klemmbretter fuer parallele Dokumentationsstationen.','Materialplanung_Aufteilung_Uni_LVR.docx'),
('Zeichenbretter A3','lmu','dokumentation',8,'Stk.','offen','mittel','Dokumentationskiste','Assistenz','4-8 Zeichenbretter; leicht zu transportieren.','Materialplanung_Aufteilung_Uni_LVR.docx'),
('Bleistifte, Radierer, Spitzer, Lineale, Geodreiecke, Massstabslineale','lmu','dokumentation',null,'Sets','offen','mittel','Teamkisten','Assistenz','Mehrere Sets plus Reserve; hoher Verbrauch, geringes Volumen.','Materialplanung_Aufteilung_Uni_LVR.docx'),
('Fundtueten, Zip-Beutel, Probenbeutel, Fundzetteltueten, Etiketten','lmu','fundverwaltung',null,null,'offen','hoch','Fundverwaltungskiste','Technische Grabungsleitung / Assistenz','Sehr grosser Vorrat fuer ca. 3 Monate; methodisch zentral.','Materialplanung_Aufteilung_Uni_LVR.docx'),
('Permanentmarker, Kreppband, Paketband, Etiketten, Stifte fuer Fundzettel','lmu','fundverwaltung',null,null,'offen','hoch','Fundverwaltungskiste','Assistenz','Marker 20-30; Kreppband 10-20 Rollen; kann auch direkt nach Kerpen geliefert werden.','Materialplanung_Aufteilung_Uni_LVR.docx'),
('Kellen und Stuckateurswerkzeuge','lmu','feinwerkzeug',20,'Stk.','offen','hoch','Teamkisten','Assistenz','Mindestens 20 Kellen; Puffer fuer Verlust, taegliche Kontrollen.','Materialplanung_Aufteilung_Uni_LVR.docx'),
('Pinsel, Zahnbuersten, Holzspatel, Plastikmesser, Spruehflaschen, Schwaemme','lmu','feinwerkzeug',4,'Team-Sets','offen','mittel','Teamkisten A-D','Assistenz','Vorrat fuer 4 Teams; leicht, guenstig, verschleissanfaellig.','Materialplanung_Aufteilung_Uni_LVR.docx'),
('Kamera, Akkus, Ladegeraete, Speicherkarten, Fotomassstaebe, Nordpfeile, Fototafeln','lmu','it_foto',1,'Set','offen','hoch','IT-/Fotokiste','Technische Grabungsleitung','1-2 Kameras; Backup-Workflow und Absprachen mit T. Simmet festlegen.','Materialplanung_Aufteilung_Uni_LVR.docx'),
('Laptop/Tablet, externe Festplatten, USB-Sticks, Powerbanks, Kartenleser','lmu','it_foto',null,null,'offen','hoch','IT-/Fotokiste','Technische Grabungsleitung','Datenhoheit und Sicherung bei Grabungsleitung.','Materialplanung_Aufteilung_Uni_LVR.docx'),
('Warnwesten, Handschuhe, Knieschoner, Schutzbrillen, Staubmasken','lmu','psa_erste_hilfe',16,'Personen + Reserve','offen','hoch','PSA-/Erste-Hilfe-Kiste','Assistenz','Groessen und Anzahl vor Beginn sichern.','Materialplanung_Aufteilung_Uni_LVR.docx'),
('Erste-Hilfe-Koffer, Zeckenzange, Augenspuelung, Notfalllisten, Desinfektion','lmu','psa_erste_hilfe',2,'Sets','offen','hoch','PSA-/Erste-Hilfe-Kiste','Technische Grabungsleitung','1-2 vollstaendige Sets; Verantwortung und Vollstaendigkeit vor Start klaeren.','Materialplanung_Aufteilung_Uni_LVR.docx'),
('Ausleihlisten, Kistenbeschriftung, farbiges Team-Klebeband, Inventaretiketten','lmu','transport_lagerung',1,'System','offen','hoch','Materialverwaltung','Assistenz','Vorab organisieren; verhindert Verlust und Chaos.','Materialplanung_Aufteilung_Uni_LVR.docx'),
('20-L-Wasserkanister','lmu','wasser',4,'Stk.','offen','mittel','Doku-/Reinigungsstation','Assistenz','2-4 Stueck; kleine Mengen, Handwaesche, Reserve. Laut Dokument ueber LMU beziehbar.','Materialplanung_Aufteilung_Uni_LVR.docx'),
('Stellenkarten','lvr','dokumentation',200,'Stk.','angefragt','hoch','vor Ort','Technische Grabungsleitung','Dokumentationssystem basiert auf Stellen; direkt anfragen.','Materialplanung_Aufteilung_Uni_LVR.docx'),
('Schaufeln','lvr','grobwerkzeug',10,'Stk.','angefragt','hoch','vor Ort','LVR / Bauhof','Mindestbedarf fuer 4 Arbeitsgruppen.','Materialplanung_Aufteilung_Uni_LVR.docx'),
('Spaten','lvr','grobwerkzeug',8,'Stk.','angefragt','hoch','vor Ort','LVR / Bauhof','Robustes Grobwerkzeug lokal organisieren.','Materialplanung_Aufteilung_Uni_LVR.docx'),
('Spitzhacken / Kreuzhacken / Hacken','lvr','grobwerkzeug',4,'Stk. je Typ','angefragt','hoch','vor Ort','LVR / Bauhof','Mindestbedarf je Typ; robust und lokal verfuegbar.','Materialplanung_Aufteilung_Uni_LVR.docx'),
('Schubkarren','lvr','grobwerkzeug',5,'Stk.','angefragt','hoch','vor Ort','LVR / Bauhof','Hoher Transportbedarf auf der Flaeche.','Materialplanung_Aufteilung_Uni_LVR.docx'),
('Grosse Besen / Strassenbesen / harte Besen','lvr','grobwerkzeug',3,'Stk.','angefragt','mittel','vor Ort','LVR / Bauhof','Mindestens 3 gesamt.','Materialplanung_Aufteilung_Uni_LVR.docx'),
('Eimer, Moertelkuebel, Moertelwannen, grosse Wannen','lvr','transport_lagerung',null,null,'angefragt','hoch','vor Ort','LVR / Bauhof','Eimer 20; Wannen 5. Eimer eventuell ueber Muenchen beziehen.','Materialplanung_Aufteilung_Uni_LVR.docx'),
('Fundkisten / Euroboxen / Stapelkisten','lvr','transport_lagerung',30,'Stk.','angefragt','hoch','vor Ort','LVR / Bauhof','Hoher Raumbedarf; weitere Kisten abrufbar halten.','Materialplanung_Aufteilung_Uni_LVR.docx'),
('Grosse Planen, Gewebeplanen, Abdeckfolien, Beschwerungen / Sandsaecke','lvr','infrastruktur',null,null,'angefragt','hoch','vor Ort','LVR / Bauhof','Mehrere Groessen fuer Flaechen- und Wetterschutz.','Materialplanung_Aufteilung_Uni_LVR.docx'),
('Pavillons / Arbeitszelte','lvr','infrastruktur',3,'Stk.','angefragt','hoch','vor Ort','LVR / lokale Partner','Moeglichst mindestens 4x4 m; Witterungsschutz fuer sensible Befunde.','Materialplanung_Aufteilung_Uni_LVR.docx'),
('Tische, Baenke / Stuehle','lvr','infrastruktur',8,'Garnituren','angefragt','hoch','vor Ort','LVR / lokale Partner','2 Schlaemmstation, 2 Grabungsbuero, 2 Grabungshaus, 2 Flaeche/Pausen.','Materialplanung_Aufteilung_Uni_LVR.docx'),
('Bauzaun, Absperrpfosten, Schlauchbruecken','lvr','infrastruktur',null,null,'angefragt','hoch','vor Ort','LVR / Kommune','Abhaengig von Gelaende, Publikumsverkehr und Arbeitsschutz.','Materialplanung_Aufteilung_Uni_LVR.docx'),
('Baustrom, outdoorfaehige Kabeltrommeln, Mehrfachsteckdosen, ggf. Generator','lvr','infrastruktur',null,null,'angefragt','hoch','vor Ort','LVR / lokale Partner','Nach Bedarf; Ladepunkt und Stromversorgung klaeren.','Materialplanung_Aufteilung_Uni_LVR.docx'),
('Hydrant als Wasserentnahmestelle','lvr','wasser',1,'Entnahmestelle','angefragt','hoch','vor Ort','LVR / Kommune / Versorger','Ober- oder Unterflurhydrant klaeren; Genehmigung und Einweisung noetig.','Materialplanung_Aufteilung_Uni_LVR.docx'),
('C-Schlaeuche','lvr','wasser',6,'Stk.','angefragt','hoch','vor Ort','LVR / Feuerwehr / Kommune','Mindestens 6; Anzahl haengt von Entfernung der Entnahmestelle ab.','Materialplanung_Aufteilung_Uni_LVR.docx'),
('Verteiler','lvr','wasser',1,'Stk.','angefragt','hoch','vor Ort','LVR / Feuerwehr / Kommune','Aufteilung fuer Wasch-/Schlaemmstation und sonstige Nutzung.','Materialplanung_Aufteilung_Uni_LVR.docx'),
('C-Strahlrohr','lvr','wasser',1,'Stk.','angefragt','mittel','vor Ort','LVR / Feuerwehr / Kommune','Kontrollierte Wasserabgabe; Nutzung nur mit Einweisung.','Materialplanung_Aufteilung_Uni_LVR.docx'),
('D-Strahlrohr mit C-D-Reduzierung','lvr','wasser',1,'Stk.','angefragt','mittel','vor Ort','LVR / Feuerwehr / Kommune','Kontrollierte Wasserabgabe; Nutzung nur mit Einweisung.','Materialplanung_Aufteilung_Uni_LVR.docx'),
('Standrohr / Hydrantenschluessel / Kupplungsschluessel','lvr','wasser',null,null,'angefragt','hoch','vor Ort','LVR / Kommune / Versorger','Abhaengig von Hydrantentyp.','Materialplanung_Aufteilung_Uni_LVR.docx'),
('Systemtrenner / Rueckflussverhinderer','lvr','wasser',null,null,'angefragt','hoch','vor Ort','Versorger / Kommune','Nach Vorgabe des Versorgers.','Materialplanung_Aufteilung_Uni_LVR.docx'),
('Schlauchbruecken / Schutzmatten','lvr','wasser',null,null,'angefragt','hoch','vor Ort','LVR / Kommune','Falls Schlaeuche Wege, Zufahrten oder Arbeitsbereiche kreuzen.','Materialplanung_Aufteilung_Uni_LVR.docx'),
('1000-L-Kanister / IBC-Container','lvr','wasser',1,'Stk.','angefragt','mittel','vor Ort','LVR / lokale Partner','Puffer oder Alternative bei eingeschraenkter Hydrantennutzung.','Materialplanung_Aufteilung_Uni_LVR.docx'),
('Drucker fuer vor Ort','privat','dokumentation',1,'Stk.','offen','hoch','Grabungsbuero','Andreas','Drucker wird privat gestellt; Kartuschen rechtzeitig beschaffen.','Materialplanung_Aufteilung_Uni_LVR.docx'),
('Druckerkartuschen','privat','verbrauch',null,'Satz','offen','hoch','Grabungsbuero','Andreas','Fuer privat gestellten Drucker; Vorrat fuer Feldzeit einplanen.','Materialplanung_Aufteilung_Uni_LVR.docx')
on conflict do nothing;
