-- Ausfalltage/-zeitraeume fuer den Personaleinsatz.
-- Additiv: legt nur eine neue Tabelle mit RLS-Policies an.

create table if not exists public.participant_absences (
  id bigint generated by default as identity primary key,
  participant_id bigint not null references public.participants(id) on delete cascade,
  absence_from date not null,
  absence_to date not null,
  reason_type text not null
    check (reason_type in ('krank','anderer_grund')),
  reason_note text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (absence_to >= absence_from),
  check (reason_type <> 'anderer_grund' or length(trim(coalesce(reason_note, ''))) > 0)
);

drop trigger if exists touch_participant_absences_updated_at on public.participant_absences;
create trigger touch_participant_absences_updated_at
before update on public.participant_absences
for each row execute function public.touch_updated_at();

alter table public.participant_absences enable row level security;

drop policy if exists "participant_absences_select_active" on public.participant_absences;
create policy "participant_absences_select_active"
on public.participant_absences for select
to authenticated
using (public.current_user_is_active());

drop policy if exists "participant_absences_insert_manager" on public.participant_absences;
create policy "participant_absences_insert_manager"
on public.participant_absences for insert
to authenticated
with check (public.current_user_can_manage());

drop policy if exists "participant_absences_update_manager" on public.participant_absences;
create policy "participant_absences_update_manager"
on public.participant_absences for update
to authenticated
using (public.current_user_can_manage())
with check (public.current_user_can_manage());

drop policy if exists "participant_absences_delete_manager" on public.participant_absences;
create policy "participant_absences_delete_manager"
on public.participant_absences for delete
to authenticated
using (public.current_user_can_manage());

grant select, insert, update, delete on public.participant_absences to authenticated;
grant usage, select on all sequences in schema public to authenticated;

notify pgrst, 'reload schema';
