-- Additive extension for multiple availability slots per participant.
-- Run once in the Supabase SQL Editor before using the plus button in Personaleinsatz.

create table if not exists public.participant_availability_slots (
  id bigint generated by default as identity primary key,
  participant_id bigint not null references public.participants(id) on delete cascade,
  availability_from date not null,
  availability_to date not null,
  order_index integer not null default 1,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (availability_to >= availability_from)
);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists touch_participant_availability_slots_updated_at on public.participant_availability_slots;
create trigger touch_participant_availability_slots_updated_at
before update on public.participant_availability_slots
for each row execute function public.touch_updated_at();

alter table public.participant_availability_slots enable row level security;

drop policy if exists "participant_availability_slots_select_active" on public.participant_availability_slots;
create policy "participant_availability_slots_select_active"
on public.participant_availability_slots for select
to authenticated
using (public.current_user_is_active());

drop policy if exists "participant_availability_slots_insert_manager" on public.participant_availability_slots;
create policy "participant_availability_slots_insert_manager"
on public.participant_availability_slots for insert
to authenticated
with check (public.current_user_can_manage());

drop policy if exists "participant_availability_slots_update_manager" on public.participant_availability_slots;
create policy "participant_availability_slots_update_manager"
on public.participant_availability_slots for update
to authenticated
using (public.current_user_can_manage())
with check (public.current_user_can_manage());

drop policy if exists "participant_availability_slots_delete_manager" on public.participant_availability_slots;
create policy "participant_availability_slots_delete_manager"
on public.participant_availability_slots for delete
to authenticated
using (public.current_user_can_manage());

grant select, insert, update, delete on public.participant_availability_slots to authenticated;
grant usage, select on all sequences in schema public to authenticated;
