-- Lehrgrabung Kerpen-Manheim 2026
-- Run this file once in the Supabase SQL Editor before running seed.sql.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  role text not null default 'viewer'
    check (role in ('admin','professor','technical_lead','assistant','trench_lead','participant','viewer')),
  is_active boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  category text not null,
  subcategory text,
  due_date date,
  status text not null default 'offen'
    check (status in ('offen','laufend','erledigt','blockiert')),
  priority text not null default 'mittel'
    check (priority in ('hoch','mittel','niedrig')),
  assigned_role text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tasks_title_unique unique (title)
);

create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  title text not null,
  body text,
  category text not null,
  subcategory text,
  note_type text not null default 'note'
    check (note_type in ('note','idea','decision')),
  status text not null default 'offen',
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint notes_title_unique unique (title)
);

-- Older setups used a fixed category check. Categories are now editable in the app,
-- so existing databases should only require a non-empty value.
alter table public.notes drop constraint if exists notes_category_check;
alter table public.notes drop constraint if exists notes_category_not_blank;
alter table public.notes
  add constraint notes_category_not_blank check (length(trim(category)) > 0);

create table if not exists public.participants (
  id bigint generated by default as identity primary key,
  full_name text not null,
  public_role text,
  availability_from date,
  availability_to date,
  status text not null default 'zu_klären'
    check (status in ('gesetzt','zugesagt','zu_klären','anzufragen')),
  availability_note text,
  source_note text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint participants_full_name_unique unique (full_name)
);

create table if not exists public.participant_private (
  participant_id bigint primary key references public.participants(id) on delete cascade,
  phone text,
  email text,
  internal_note text,
  updated_at timestamptz not null default now()
);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists touch_profiles_updated_at on public.profiles;
create trigger touch_profiles_updated_at
before update on public.profiles
for each row execute function public.touch_updated_at();

drop trigger if exists touch_tasks_updated_at on public.tasks;
create trigger touch_tasks_updated_at
before update on public.tasks
for each row execute function public.touch_updated_at();

drop trigger if exists touch_notes_updated_at on public.notes;
create trigger touch_notes_updated_at
before update on public.notes
for each row execute function public.touch_updated_at();

drop trigger if exists touch_participants_updated_at on public.participants;
create trigger touch_participants_updated_at
before update on public.participants
for each row execute function public.touch_updated_at();

drop trigger if exists touch_participant_private_updated_at on public.participant_private;
create trigger touch_participant_private_updated_at
before update on public.participant_private
for each row execute function public.touch_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name, role, is_active)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'full_name', new.email),
    'viewer',
    false
  )
  on conflict (id) do update
    set email = excluded.email,
        full_name = coalesce(public.profiles.full_name, excluded.full_name);
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.current_user_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select role from public.profiles where id = auth.uid();
$$;

create or replace function public.current_user_is_active()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(is_active, false) from public.profiles where id = auth.uid();
$$;

create or replace function public.current_user_can_manage()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.current_user_role() in ('admin','professor','technical_lead','assistant');
$$;

alter table public.profiles enable row level security;
alter table public.tasks enable row level security;
alter table public.notes enable row level security;
alter table public.participants enable row level security;
alter table public.participant_private enable row level security;

drop policy if exists "profiles_select_own_or_admin" on public.profiles;
create policy "profiles_select_own_or_admin"
on public.profiles for select
to authenticated
using (id = auth.uid() or public.current_user_role() = 'admin');

drop policy if exists "profiles_update_admin" on public.profiles;
create policy "profiles_update_admin"
on public.profiles for update
to authenticated
using (public.current_user_role() = 'admin')
with check (public.current_user_role() = 'admin');

drop policy if exists "tasks_select_active" on public.tasks;
create policy "tasks_select_active"
on public.tasks for select
to authenticated
using (public.current_user_is_active());

drop policy if exists "tasks_insert_active" on public.tasks;
create policy "tasks_insert_active"
on public.tasks for insert
to authenticated
with check (public.current_user_is_active());

drop policy if exists "tasks_update_owner_or_manager" on public.tasks;
create policy "tasks_update_owner_or_manager"
on public.tasks for update
to authenticated
using (created_by = auth.uid() or public.current_user_can_manage())
with check (created_by = auth.uid() or public.current_user_can_manage());

drop policy if exists "notes_select_active" on public.notes;
create policy "notes_select_active"
on public.notes for select
to authenticated
using (public.current_user_is_active());

drop policy if exists "notes_insert_active" on public.notes;
create policy "notes_insert_active"
on public.notes for insert
to authenticated
with check (public.current_user_is_active());

drop policy if exists "notes_update_owner_or_manager" on public.notes;
create policy "notes_update_owner_or_manager"
on public.notes for update
to authenticated
using (created_by = auth.uid() or public.current_user_can_manage())
with check (created_by = auth.uid() or public.current_user_can_manage());

drop policy if exists "participants_select_active" on public.participants;
create policy "participants_select_active"
on public.participants for select
to authenticated
using (public.current_user_is_active());

drop policy if exists "participants_insert_manager" on public.participants;
create policy "participants_insert_manager"
on public.participants for insert
to authenticated
with check (public.current_user_can_manage());

drop policy if exists "participants_update_manager" on public.participants;
create policy "participants_update_manager"
on public.participants for update
to authenticated
using (public.current_user_can_manage())
with check (public.current_user_can_manage());

drop policy if exists "participant_private_select_manager" on public.participant_private;
create policy "participant_private_select_manager"
on public.participant_private for select
to authenticated
using (public.current_user_can_manage());

drop policy if exists "participant_private_insert_manager" on public.participant_private;
create policy "participant_private_insert_manager"
on public.participant_private for insert
to authenticated
with check (public.current_user_can_manage());

drop policy if exists "participant_private_update_manager" on public.participant_private;
create policy "participant_private_update_manager"
on public.participant_private for update
to authenticated
using (public.current_user_can_manage())
with check (public.current_user_can_manage());

grant usage on schema public to anon, authenticated;
grant select, insert, update on public.profiles to authenticated;
grant select, insert, update on public.tasks to authenticated;
grant select, insert, update on public.notes to authenticated;
grant select, insert, update on public.participants to authenticated;
grant select, insert, update on public.participant_private to authenticated;
grant usage, select on all sequences in schema public to authenticated;
