import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js/+esm';

const EDIT_ROLES = ['admin','technical_lead','assistant'];
const IMPORT_ROLES = ['admin','technical_lead'];
const EXPORT_ROLES = ['admin','technical_lead','assistant'];
const DELETE_ROLES = ['admin','technical_lead'];
const STATUS = ['geplant','aktiv','prüfen','erledigt','archiv'];
const PRIORITIES = ['hoch','mittel','niedrig'];
const STYLES = {
  standard:{version:8,sources:{osm:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenStreetMap contributors'}},layers:[{id:'osm',type:'raster',source:'osm'}]},
  satellite:{version:8,sources:{esri:{type:'raster',tiles:['https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}'],tileSize:256,attribution:'Tiles © Esri'}},layers:[{id:'esri',type:'raster',source:'esri'}]},
  topo:{version:8,sources:{topo:{type:'raster',tiles:['https://tile.opentopomap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenTopoMap contributors'}},layers:[{id:'topo',type:'raster',source:'topo'}]}
};

const s = {db:null,session:null,profile:null,map:null,draw:null,layers:[],features:[],tasks:[],people:[],visible:new Set(),selectedId:null,geometry:null,ready:false,labels:true,filters:{layer:'alle',category:'alle',status:'alle',role:'alle',q:''}};
const el = {};
document.addEventListener('DOMContentLoaded', install);

function install(){injectAssets();injectNav();injectTab();cache();bind();}
function injectAssets(){[['maplibreCss','https://cdn.jsdelivr.net/npm/maplibre-gl@5.9.0/dist/maplibre-gl.css'],['mapDrawCss','https://cdn.jsdelivr.net/npm/@mapbox/mapbox-gl-draw@1.5.0/dist/mapbox-gl-draw.css'],['mapModuleCss','./map-module.css']].forEach(([id,href])=>{if(document.getElementById(id))return;const l=document.createElement('link');l.id=id;l.rel='stylesheet';l.href=href;document.head.appendChild(l);});}
function injectNav(){const nav=document.querySelector('.nav');if(!nav||document.querySelector('[data-map-tab]'))return;const b=document.createElement('button');b.className='nav-btn';b.type='button';b.dataset.mapTab='map';b.textContent='Karte';nav.insertBefore(b,nav.querySelector('[data-tab="tasks"]'));b.addEventListener('click',showTab);}
function injectTab(){const main=document.querySelector('.main');if(!main||document.getElementById('mapTab'))return;const sec=document.createElement('section');sec.id='mapTab';sec.className='tab';sec.innerHTML=`
<div class="section-head"><div><h3>Kartenmodul</h3><p class="muted">Räumliche Organisation, Infrastruktur und Einsatzsteuerung.</p></div><div class="button-row"><button class="btn small" id="mapReloadButton" type="button">Neu laden</button><button class="btn small" id="mapExportAllButton" type="button">GeoJSON exportieren</button></div></div>
<div class="map-shell"><aside class="map-panel map-sidebar"><h3>Layer & Filter</h3><div class="map-filter-stack">
<label>Basiskarte<select id="mapBaseStyle"><option value="standard">Standardkarte</option><option value="satellite">Satellit</option><option value="topo">Gelände / Topografie</option></select></label>
<label>Suche Ort / Koordinaten<input id="mapSearchInput" type="search" placeholder="Kerpen, 50.87, 6.69"></label><button class="btn small" id="mapSearchButton" type="button">Suchen</button>
<label>Layer<select id="mapLayerFilter"><option value="alle">Alle Layer</option></select></label><label>Kategorie<select id="mapCategoryFilter"><option value="alle">Alle Kategorien</option></select></label><label>Status<select id="mapStatusFilter"><option value="alle">Alle Status</option></select></label><label>Rolle<select id="mapRoleFilter"><option value="alle">Alle Rollen</option></select></label><label>Titel / Beschreibung<input id="mapTextFilter" type="search"></label><label><input id="mapLabelsToggle" type="checkbox" checked> Labels anzeigen</label></div>
<div id="mapLayerList" class="map-layer-list"></div><form id="mapLayerForm" class="map-form hidden"><h4>Layer anlegen</h4><label>Name<input name="name" required></label><label>Farbe<input name="color" type="color" value="#2d7dd2"></label><label>Beschreibung<textarea name="description" rows="2"></textarea></label><button class="btn primary small" type="submit">Layer speichern</button></form><div class="map-import-row"><label>Import GeoJSON / Shape-ZIP<input id="mapImportFile" type="file" accept=".geojson,.json,.zip"></label><button class="btn small" id="mapImportButton" type="button">Importieren</button></div><div id="mapStatus" class="map-status"></div></aside>
<section class="map-stage"><div class="map-toolbar"><button class="btn small" data-draw="simple_select" type="button">Ansicht</button><button class="btn small" data-draw="draw_point" type="button">Punkt</button><button class="btn small" data-draw="draw_line_string" type="button">Linie</button><button class="btn small" data-draw="draw_polygon" type="button">Fläche</button><button class="btn small" id="mapDeleteGeometryButton" type="button">Geometrie löschen</button><button class="btn small" id="mapFitButton" type="button">Auf Daten zoomen</button></div><div id="excavationMap"></div></section>
<aside class="map-panel map-detail"><h3>Objektdetails</h3><div id="mapReadonlyHint" class="map-readonly hidden">Leserechte. Bearbeiten ist für diese Rolle deaktiviert.</div><form id="mapFeatureForm" class="map-form"><label>Titel<input name="title" required></label><label>Layer<select name="primary_layer_id" required></select></label><label>Kategorie<input name="category"></label><label>Status<select name="status"></select></label><label>Priorität<select name="priority"></select></label><label>Verantwortliche Rolle<input name="responsible_role"></label><label>Verknüpfte Aufgabe<select name="linked_task_id"><option value="">Keine</option></select></label><label>Verknüpfte Person<select name="linked_participant_id"><option value="">Keine</option></select></label><label>Label<input name="label"></label><label>Beschreibung<textarea name="description" rows="5"></textarea></label><div class="button-row"><button class="btn primary" type="submit">Objekt speichern</button><button class="btn" id="mapNewFeatureButton" type="button">Neu</button><button class="btn ghost" id="mapDeleteFeatureButton" type="button">Löschen</button></div></form></aside></div>`;main.insertBefore(sec,document.getElementById('helpTab'));}
function cache(){['mapTab','mapReloadButton','mapExportAllButton','mapBaseStyle','mapSearchInput','mapSearchButton','mapLayerFilter','mapCategoryFilter','mapStatusFilter','mapRoleFilter','mapTextFilter','mapLabelsToggle','mapLayerList','mapLayerForm','mapImportFile','mapImportButton','mapStatus','excavationMap','mapDeleteGeometryButton','mapFitButton','mapFeatureForm','mapReadonlyHint','mapNewFeatureButton','mapDeleteFeatureButton'].forEach(id=>el[id]=document.getElementById(id));}
function bind(){el.mapReloadButton?.addEventListener('click',()=>loadData(true));el.mapExportAllButton?.addEventListener('click',()=>download(fc(filtered()),'lehrgrabung-karte.geojson'));el.mapBaseStyle?.addEventListener('change',switchStyle);el.mapSearchButton?.addEventListener('click',search);el.mapLabelsToggle?.addEventListener('change',()=>{s.labels=el.mapLabelsToggle.checked;renderMap();});['mapLayerFilter','mapCategoryFilter','mapStatusFilter','mapRoleFilter','mapTextFilter'].forEach(id=>el[id]?.addEventListener('input',filters));document.querySelectorAll('[data-draw]').forEach(b=>b.addEventListener('click',()=>drawMode(b.dataset.draw)));el.mapDeleteGeometryButton?.addEventListener('click',()=>{s.draw.deleteAll();s.geometry=null;msg('Geometrie entfernt.');});el.mapFitButton?.addEventListener('click',fit);el.mapFeatureForm?.addEventListener('submit',saveFeature);el.mapNewFeatureButton?.addEventListener('click',newFeature);el.mapDeleteFeatureButton?.addEventListener('click',deleteFeature);el.mapLayerForm?.addEventListener('submit',saveLayer);el.mapImportButton?.addEventListener('click',importFile);}
async function showTab(){document.querySelectorAll('.nav-btn').forEach(b=>b.classList.remove('active'));document.querySelector('[data-map-tab]')?.classList.add('active');document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));el.mapTab.classList.add('active');document.getElementById('pageTitle').textContent='Karte';document.getElementById('pageSubtitle').textContent='Grabungsorganisation, Infrastruktur und Einsatzsteuerung';await init();}
async function init(){if(s.ready){s.map.resize();return;}msg('Kartenmodul wird geladen ...');s.db=createClient(window.APP_CONFIG.SUPABASE_URL,window.APP_CONFIG.SUPABASE_ANON_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});s.session=(await s.db.auth.getSession()).data.session;if(!s.session)return msg('Bitte anmelden.',true);s.profile=(await s.db.from('profiles').select('*').eq('id',s.session.user.id).single()).data;await libs();initMap();await loadData();permissions();s.ready=true;msg('Karte synchronisiert.',false,true);}
async function libs(){if(!window.maplibregl)await script('https://cdn.jsdelivr.net/npm/maplibre-gl@5.9.0/dist/maplibre-gl.js');if(!window.MapboxDraw)await script('https://cdn.jsdelivr.net/npm/@mapbox/mapbox-gl-draw@1.5.0/dist/mapbox-gl-draw.js');window.mapboxgl=window.maplibregl;}
function script(src){return new Promise((ok,fail)=>{const e=document.createElement('script');e.src=src;e.onload=ok;e.onerror=()=>fail(new Error('Bibliothek konnte nicht geladen werden: '+src));document.head.appendChild(e);});}
function initMap(){s.map=new maplibregl.Map({container:'excavationMap',style:STYLES.standard,center:[6.64,50.87],zoom:13});s.map.addControl(new maplibregl.NavigationControl({visualizePitch:true}),'top-right');s.map.addControl(new maplibregl.FullscreenControl(),'top-right');s.map.addControl(new maplibregl.ScaleControl({unit:'metric'}),'bottom-left');s.draw=new MapboxDraw({displayControlsDefault:false,controls:{},userProperties:true});s.map.addControl(s.draw,'top-left');s.map.on('load',renderMap);s.map.on('styledata',renderMap);['map-points','map-lines','map-polygons-fill'].forEach(id=>s.map.on('click',id,selectMap));s.map.on('draw.create',e=>{const f=e.features[0];s.geometry=f.geometry;s.selectedId=null;if(!el.mapFeatureForm.elements.title.value)el.mapFeatureForm.elements.title.value=f.geometry.type==='Point'?'Neuer Punkt':f.geometry.type==='LineString'?'Neue Linie':'Neue Fläche';msg('Geometrie erfasst. Attribute ergänzen und speichern.');});s.map.on('draw.update',async e=>{const f=e.features[0];s.geometry=f.geometry;const id=Number(String(f.id).replace('db-',''));if(id&&canEdit())await s.db.from('map_features').update({geometry:f.geometry,geometry_type:f.geometry.type,updated_by:s.session.user.id}).eq('id',id),await loadData();});}
async function loadData(done=false){msg('Lade Kartendaten ...');const [l,f,t,p]=await Promise.all([s.db.from('map_layers').select('*').order('sort_order').order('name'),s.db.from('map_features').select('*').order('updated_at',{ascending:false}),s.db.from('tasks').select('id,title').order('title'),s.db.from('participants').select('id,full_name').order('full_name')]);const er=l.error||f.error||t.error||p.error;if(er)return msg(er.message,true);s.layers=l.data||[];s.features=f.data||[];s.tasks=t.data||[];s.people=p.data||[];s.visible=new Set(s.layers.filter(x=>x.is_visible!==false).map(x=>Number(x.id)));renderControls();renderMap();if(done)msg('Kartendaten neu geladen.',false,true);}
function permissions(){const edit=canEdit();el.mapReadonlyHint.classList.toggle('hidden',edit);el.mapFeatureForm.querySelectorAll('input,select,textarea,button').forEach(x=>x.disabled=!edit);document.querySelectorAll('[data-draw],#mapDeleteGeometryButton').forEach(x=>x.disabled=!edit);el.mapImportButton.disabled=!IMPORT_ROLES.includes(s.profile?.role);el.mapImportFile.disabled=el.mapImportButton.disabled;el.mapExportAllButton.disabled=!EXPORT_ROLES.includes(s.profile?.role);el.mapLayerForm.classList.toggle('hidden',s.profile?.role!=='admin');}
function renderControls(){el.mapLayerList.innerHTML=s.layers.map(l=>`<label class="map-layer-row"><input type="checkbox" data-vis="${l.id}" ${s.visible.has(Number(l.id))?'checked':''}><span><span class="map-color-dot" style="background:${esc(l.color)}"></span>${esc(l.name)}</span><button class="btn small" type="button" data-export="${l.id}">Export</button></label>`).join('');el.mapLayerList.querySelectorAll('[data-vis]').forEach(i=>i.addEventListener('change',()=>{const id=Number(i.dataset.vis);i.checked?s.visible.add(id):s.visible.delete(id);renderMap();}));el.mapLayerList.querySelectorAll('[data-export]').forEach(b=>b.addEventListener('click',()=>download(fc(s.features.filter(f=>Number(f.primary_layer_id)===Number(b.dataset.export))),`layer-${b.dataset.export}.geojson`)));opts(el.mapLayerFilter,[['alle','Alle Layer'],...s.layers.map(l=>[l.id,l.name])]);opts(el.mapCategoryFilter,[['alle','Alle Kategorien'],...[...new Set(s.features.map(f=>f.category).filter(Boolean))].map(v=>[v,v])]);opts(el.mapStatusFilter,[['alle','Alle Status'],...STATUS.map(v=>[v,v])]);opts(el.mapRoleFilter,[['alle','Alle Rollen'],...[...new Set(s.features.map(f=>f.responsible_role).filter(Boolean))].map(v=>[v,v])]);opts(el.mapFeatureForm.elements.primary_layer_id,s.layers.map(l=>[l.id,l.name]));opts(el.mapFeatureForm.elements.status,STATUS.map(v=>[v,v]),'geplant');opts(el.mapFeatureForm.elements.priority,PRIORITIES.map(v=>[v,v]),'mittel');opts(el.mapFeatureForm.elements.linked_task_id,[['','Keine'],...s.tasks.map(t=>[t.id,t.title])]);opts(el.mapFeatureForm.elements.linked_participant_id,[['','Keine'],...s.people.map(p=>[p.id,p.full_name])]);}
function opts(sel,pairs,selected=''){if(sel)sel.innerHTML=pairs.map(([v,l])=>`<option value="${esc(v)}" ${String(v)===String(selected)?'selected':''}>${esc(l)}</option>`).join('');}
function renderMap(){if(!s.map||!s.map.isStyleLoaded())return;const data=fc(filtered());if(!s.map.getSource('map-features')){s.map.addSource('map-features',{type:'geojson',data});s.map.addLayer({id:'map-polygons-fill',type:'fill',source:'map-features',filter:['in',['geometry-type'],['literal',['Polygon','MultiPolygon']]],paint:{'fill-color':['get','color'],'fill-opacity':0.28}});s.map.addLayer({id:'map-polygons-outline',type:'line',source:'map-features',filter:['in',['geometry-type'],['literal',['Polygon','MultiPolygon']]],paint:{'line-color':['get','color'],'line-width':2}});s.map.addLayer({id:'map-lines',type:'line',source:'map-features',filter:['in',['geometry-type'],['literal',['LineString','MultiLineString']]],paint:{'line-color':['get','color'],'line-width':4}});s.map.addLayer({id:'map-points',type:'circle',source:'map-features',filter:['in',['geometry-type'],['literal',['Point','MultiPoint']]],paint:{'circle-radius':7,'circle-color':['get','color'],'circle-stroke-width':2,'circle-stroke-color':'#fff'}});s.map.addLayer({id:'map-labels',type:'symbol',source:'map-features',layout:{'text-field':['get','label'],'text-size':12,'text-offset':[0,1.2],'text-anchor':'top'},paint:{'text-color':'#0b2239','text-halo-color':'#fff','text-halo-width':1.2}});}else s.map.getSource('map-features').setData(data);s.map.setLayoutProperty('map-labels','visibility',s.labels?'visible':'none');}
function filtered(){return s.features.filter(f=>{const lid=Number(f.primary_layer_id);if(!s.visible.has(lid))return false;if(s.filters.layer!=='alle'&&String(lid)!==s.filters.layer)return false;if(s.filters.category!=='alle'&&f.category!==s.filters.category)return false;if(s.filters.status!=='alle'&&f.status!==s.filters.status)return false;if(s.filters.role!=='alle'&&f.responsible_role!==s.filters.role)return false;if(s.filters.q&&!`${f.title||''} ${f.description||''} ${f.label||''}`.toLowerCase().includes(s.filters.q.toLowerCase()))return false;return true;});}
function fc(rows){return{type:'FeatureCollection',features:rows.filter(r=>r.geometry).map(r=>{const l=s.layers.find(x=>Number(x.id)===Number(r.primary_layer_id));return{type:'Feature',id:r.id,geometry:r.geometry,properties:{id:r.id,title:r.title,label:r.label||r.title||'',category:r.category||'',status:r.status||'',priority:r.priority||'',color:l?.color||'#2d7dd2',layer_name:l?.name||'Layer'}};})};}
function selectMap(e){const id=Number(e.features?.[0]?.properties?.id);const r=s.features.find(f=>Number(f.id)===id);if(!r)return;s.selectedId=r.id;s.geometry=r.geometry;fillForm(r);new maplibregl.Popup().setLngLat(e.lngLat).setHTML(`<div class="map-popup-title">${esc(r.title)}</div><div class="map-popup-meta">${esc(r.status||'')}</div>`).addTo(s.map);if(canEdit()){s.draw.deleteAll();s.draw.add({type:'Feature',id:`db-${r.id}`,geometry:r.geometry,properties:{dbId:r.id}});s.draw.changeMode('simple_select',{featureIds:[`db-${r.id}`]});}}
function fillForm(r){const f=el.mapFeatureForm.elements;f.title.value=r.title||'';f.primary_layer_id.value=r.primary_layer_id||'';f.category.value=r.category||'';f.status.value=r.status||'geplant';f.priority.value=r.priority||'mittel';f.responsible_role.value=r.responsible_role||'';f.linked_task_id.value=r.linked_task_id||'';f.linked_participant_id.value=r.linked_participant_id||'';f.label.value=r.label||'';f.description.value=r.description||'';}
function newFeature(){s.selectedId=null;s.geometry=null;s.draw?.deleteAll();el.mapFeatureForm.reset();renderControls();msg('Werkzeug wählen und neues Objekt zeichnen.');}
async function saveFeature(e){e.preventDefault();if(!canEdit())return msg('Keine Bearbeitungsrechte.',true);const fd=new FormData(e.currentTarget);const g=s.geometry||s.draw.getAll().features?.[0]?.geometry;if(!g)return msg('Bitte zuerst eine Geometrie zeichnen oder auswählen.',true);const p={title:String(fd.get('title')||'').trim(),description:String(fd.get('description')||'').trim()||null,primary_layer_id:Number(fd.get('primary_layer_id')),geometry:g,geometry_type:g.type,category:String(fd.get('category')||'').trim()||null,status:String(fd.get('status')||'geplant'),priority:String(fd.get('priority')||'mittel'),responsible_role:String(fd.get('responsible_role')||'').trim()||null,linked_task_id:fd.get('linked_task_id')?Number(fd.get('linked_task_id')):null,linked_participant_id:fd.get('linked_participant_id')?Number(fd.get('linked_participant_id')):null,label:String(fd.get('label')||'').trim()||String(fd.get('title')||'').trim(),properties:{}};if(!p.title||!p.primary_layer_id)return msg('Titel und Layer sind Pflicht.',true);const q=s.selectedId?s.db.from('map_features').update({...p,updated_by:s.session.user.id}).eq('id',s.selectedId):s.db.from('map_features').insert({...p,created_by:s.session.user.id,updated_by:s.session.user.id}).select('id').single();const {data,error}=await q;if(error)return msg(error.message,true);if(data?.id)s.selectedId=data.id;await loadData();msg('Objekt gespeichert.',false,true);}
async function deleteFeature(){if(!DELETE_ROLES.includes(s.profile?.role))return msg('Keine Löschrechte.',true);if(!s.selectedId)return msg('Kein Objekt ausgewählt.',true);if(!confirm('Kartenobjekt wirklich löschen?'))return;const {error}=await s.db.from('map_features').delete().eq('id',s.selectedId);if(error)return msg(error.message,true);s.selectedId=null;s.geometry=null;s.draw.deleteAll();el.mapFeatureForm.reset();await loadData();msg('Objekt gelöscht.',false,true);}
async function saveLayer(e){e.preventDefault();if(s.profile?.role!=='admin')return msg('Nur Admins können Layer anlegen.',true);const fd=new FormData(e.currentTarget);const name=String(fd.get('name')||'').trim();if(!name)return;const {error}=await s.db.from('map_layers').insert({name,slug:slug(name),color:String(fd.get('color')||'#2d7dd2'),description:String(fd.get('description')||'').trim()||null,created_by:s.session.user.id});if(error)return msg(error.message,true);e.currentTarget.reset();await loadData();msg('Layer gespeichert.',false,true);}
async function importFile(){if(!IMPORT_ROLES.includes(s.profile?.role))return msg('Keine Importrechte.',true);const file=el.mapImportFile.files?.[0];if(!file)return msg('Datei auswählen.',true);const layerId=el.mapLayerFilter.value!=='alle'?Number(el.mapLayerFilter.value):Number(el.mapFeatureForm.elements.primary_layer_id.value||s.layers[0]?.id);if(!layerId)return msg('Ziel-Layer fehlt.',true);try{msg('Import läuft ...');const c=await readFile(file);const rows=normalize(c).map(f=>({title:String(f.properties?.title||f.properties?.name||'Importiertes Objekt'),description:f.properties?.description||null,primary_layer_id:layerId,geometry:f.geometry,geometry_type:f.geometry.type,category:f.properties?.category||null,status:f.properties?.status||'geplant',priority:f.properties?.priority||'mittel',responsible_role:f.properties?.responsible_role||null,label:f.properties?.label||f.properties?.name||f.properties?.title||null,properties:f.properties||{},created_by:s.session.user.id,updated_by:s.session.user.id}));if(!rows.length)return msg('Keine gültigen Geometrien gefunden.',true);const {error}=await s.db.from('map_features').insert(rows);if(error)throw error;await loadData();msg(`${rows.length} Objekt(e) importiert.`,false,true);}catch(err){msg(err.message||String(err),true);}}
async function readFile(file){if(file.name.toLowerCase().endsWith('.zip')){if(!window.shp)await script('https://cdn.jsdelivr.net/npm/shpjs@6.1.0/dist/shp.min.js');return window.shp(await file.arrayBuffer());}return JSON.parse(await file.text());}
function normalize(data){const c=Array.isArray(data)?data[0]:data;const fs=c?.type==='FeatureCollection'?c.features:c?.type==='Feature'?[c]:[];return fs.filter(f=>['Point','LineString','Polygon','MultiPoint','MultiLineString','MultiPolygon'].includes(f.geometry?.type));}
async function search(){const q=el.mapSearchInput.value.trim();if(!q)return;const c=parseCoord(q);if(c)return s.map.flyTo({center:c,zoom:17});const r=await fetch('https://nominatim.openstreetmap.org/search?format=json&limit=1&q='+encodeURIComponent(q));const first=(await r.json())[0];if(!first)return msg('Ort nicht gefunden.',true);s.map.flyTo({center:[Number(first.lon),Number(first.lat)],zoom:16});}
function parseCoord(v){const m=v.match(/(-?\d+(?:\.\d+)?)\s*[,; ]\s*(-?\d+(?:\.\d+)?)/);if(!m)return null;const a=Number(m[1]),b=Number(m[2]);if(Math.abs(a)<=90&&Math.abs(b)<=180)return[b,a];if(Math.abs(a)<=180&&Math.abs(b)<=90)return[a,b];return null;}
function switchStyle(){const center=s.map.getCenter(),zoom=s.map.getZoom();s.map.setStyle(STYLES[el.mapBaseStyle.value]||STYLES.standard);s.map.once('styledata',()=>{renderMap();s.map.jumpTo({center,zoom});});}
function drawMode(mode){if(!canEdit())return;s.draw.changeMode(mode);document.querySelectorAll('[data-draw]').forEach(b=>b.classList.toggle('active',b.dataset.draw===mode));}
function filters(){s.filters={layer:el.mapLayerFilter.value||'alle',category:el.mapCategoryFilter.value||'alle',status:el.mapStatusFilter.value||'alle',role:el.mapRoleFilter.value||'alle',q:el.mapTextFilter.value||''};renderMap();}
function fit(){const rows=filtered();if(!rows.length)return;const b=new maplibregl.LngLatBounds();fc(rows).features.forEach(f=>coords(f.geometry.coordinates,c=>b.extend(c)));s.map.fitBounds(b,{padding:50,maxZoom:18});}
function coords(c,cb){if(typeof c[0]==='number')return cb(c);c.forEach(x=>coords(x,cb));}
function download(data,name){if(!EXPORT_ROLES.includes(s.profile?.role))return msg('Keine Exportrechte.',true);const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/geo+json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}
function canEdit(){return EDIT_ROLES.includes(s.profile?.role);}function msg(t,err=false,ok=false){if(!el.mapStatus)return;el.mapStatus.textContent=t;el.mapStatus.classList.toggle('error',err);el.mapStatus.classList.toggle('success',ok);}function slug(v){return String(v).toLowerCase().trim().replaceAll('ä','ae').replaceAll('ö','oe').replaceAll('ü','ue').replaceAll('ß','ss').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');}function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');}
